# ====================================================================
# 1. 도커 스웜 최초 초기화(init)를 수행할 메인 매니저 리더 노드
# ====================================================================
[swarm_manager_leader]
swarm-mg  ansible_host=192.168.100.20

# ====================================================================
# 2. 리더 노드가 생성한 매니저 토큰을 받아 추가 매니저로 조인할 노드들
# ====================================================================
[swarm_manager_nodes]
swarm-mg2 ansible_host=192.168.100.21
swarm-mg3 ansible_host=192.168.100.22

# ====================================================================
# [추가 예정] 3. 독립된 백엔드 데이터베이스 노드 (주석 처리됨)
# ====================================================================
# [db_nodes]
# db-node1 ansible_host=192.168.101.31
# db-node2 ansible_host=192.168.101.32

# ====================================================================
# 4. 전체 노드들을 하나로 묶어주는 클러스터 상위 그룹
# ====================================================================
[swarm_cluster:children]
swarm_manager_leader
swarm_manager_nodes
# db_nodes # 나중에 DB 노드를 활성화할 때 이 주석도 함께 풀어주세요.

# ====================================================================
# 5. 모든 가상 머신에 공통으로 적용할 SSH 접속 및 비밀키 변수 설정
# ====================================================================
[swarm_cluster:vars]
ansible_user=ubuntu
# 프로젝트 루트 폴더 내에 위치한 my-key.pem 파일을 바라봅니다.
ansible_ssh_private_key_file=~/ansible-project/my-key.pem
