---
- name: Get service name to rollback
  shell: docker service ls --format '{{ "{{" }}.Name{{ "}}" }} {{ "{{" }}.Image{{ "}}" }}' | grep "{{ image_repo }}" | awk '{print $1}'
  register: service_name
  failed_when: false  # 💡 서비스가 검색되지 않아도 플레이북이 강제 종료되지 않도록 방어
  changed_when: false

- name: Rollback service to previous configuration
  shell: "docker service rollback {{ service_name.stdout }}"
  when: service_name.stdout != ""  # 💡 실제로 발견된 서비스 명이 존재할 때만 롤백 명령 실행
