- name: Swarm join
  block:
    - name: Check swarm state
      shell: sudo docker info --format '{{ "{{" }}.Swarm.LocalNodeState{{ "}}" }}'
      register: swarm_state
      changed_when: false

    - name: Join swarm as manager
      shell: docker swarm join --token {{ hostvars['swarm-mg']['swarm_manager_token'] }} {{ hostvars['swarm-mg']['ansible_host'] }}:2377
      when: swarm_state.stdout != "active"

  rescue:
    - name: Leave swarm on failure
      shell: sudo docker swarm leave --force
      ignore_errors: yes

    - name: Retry join swarm
      shell: docker swarm join --token {{ hostvars['swarm-mg']['swarm_manager_token'] }} {{ hostvars['swarm-mg']['ansible_host'] }}:2377

