---
- name: Docker Swarm 글로벌 서비스를 이용해 모든 Swarm 노드에 cAdvisor 컨테이너 배포
  shell: |
    docker service create \
      --name cadvisor \
      --mode global \
      --mount type=bind,src=/,dst=/rootfs,ro \
      --mount type=bind,src=/var/run,dst=/var/run,ro \
      --mount type=bind,src=/sys,dst=/sys,ro \
      --mount type=bind,src=/var/lib/docker/,dst=/var/lib/docker,ro \
      --mount type=bind,src=/dev/disk/,dst=/dev/disk,ro \
      --publish published=8080,target=8080,mode=host \
      google/cadvisor:latest
  args:
    # 이미 서비스가 띄워져 있다면 중복 에러가 나지 않도록 예외 처리
    removes: /var/run/docker.sock
  failed_when: false
