---
- name: Check if cAdvisor service already exists
  shell: docker service inspect cadvisor
  register: cadvisor_check
  failed_when: false
  changed_when: false
  # 💡 오직 swarm-mg(리더)에서만 실행되도록 강제 위임
  delegate_to: swarm-mg

- name: Deploy cAdvisor Global Service on Swarm Cluster
  shell: |
    docker service create \
      --name cadvisor \
      --mode global \
      --mount type=bind,src=/,dst=/rootfs,ro \
      --mount type=bind,src=/var/run,dst=/var/run,ro \
      --mount type=bind,src=/sys,dst=/sys,ro \
      --mount type=bind,src=/var/lib/docker/,dst=/var/lib/docker,ro \
      --mount type=bind,src=/dev/disk/,dst=/dev/disk,ro \
      --publish published=8080,target=8080,mode=host \
      google/cadvisor:latest
  when: cadvisor_check.rc != 0  # 💡 서비스가 없을 때만 최초 1회 실행
  delegate_to: swarm-mg         # 💡 오직 swarm-mg(리더)에서만 실행되도록 강제 위임

