---
- name: Docker setup
  block:
    - name: Update apt repository cache
      apt:
        update_cache: yes

    - name: Install Docker from Ubuntu official repository
      apt:
        name:
          - docker.io
        state: present

    - name: Start and Enable Docker Service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

  rescue:
    - name: Clean up on failure
      apt:
        name: docker.io
        state: absent
