- name: Swarm init
  block:
    - name: Init swarm
      shell: docker swarm init --advertise-addr {{ ansible_host }}
      args:
        creates: /var/lib/docker/swarm/state.json

    - name: Get manager join token
      shell: docker swarm join-token manager -q
      register: manager_token

    - name: Save token
      set_fact:
        swarm_manager_token: "{{ manager_token.stdout }}"

  rescue:
    - name: Leave swarm on failure
      shell: sudo docker swarm leave --force
      ignore_errors: yes

