- targets:
    - 192.168.100.20:8080
  labels:
    node: swarm-mg
    role: swarm-manager
    layer: openstack-instance

- targets:
    - 192.168.100.21:8080
  labels:
    node: swarm-mg2
    role: swarm-manager
    layer: openstack-instance

- targets:
    - 192.168.100.22:8080
  labels:
    node: swarm-mg3
    role: swarm-manager
    layer: openstack-instance

#- targets:
#    - 192.168.100.23:8080
#  labels:
#    node: worker-01
#    role: swarm-worker
#    layer: openstack-instance
