- targets:
    - 192.168.101.31:9104
  labels:
    node: db01
    role: database
    layer: openstack-instance
    db_role: primary

- targets:
    - 192.168.101.32:9104
  labels:
    node: db02
    role: database
    layer: openstack-instance
    db_role: replica