[master]
master ansible_host=192.168.100.10
# 외부 bastion 접속 시: ansible_host=172.16.8.146

[swarm_manager]
swarm-mg ansible_host=192.168.100.20

[swarm_workers]
swarm-worker ansible_host=192.168.100.21

[monitoring]
monitor ansible_host=192.168.100.40

[database]
db01 ansible_host=192.168.101.31
db02 ansible_host=192.168.101.32

[all:vars]
ansible_user=ubuntu
ansible_become=true
ansible_ssh_private_key_file=~/.ssh/project-key
ansible_python_interpreter=/usr/bin/python3
