[swarm_managers]
# 192.168.100.X 대역을 사용하는 Swarm 제어 및 웹/WAS 겸임 노드들
swarm-mg    ansible_host={{ swarm_mg_host }}    swarm_ip=192.168.100.20
swarm-mg2   ansible_host={{ swarm_mg2_host }}   swarm_ip=192.168.100.21
swarm-mg3   ansible_host={{ swarm_mg3_host }}   swarm_ip=192.168.100.22

[databases]
# 192.168.101.X 대역을 사용하는 MariaDB Primary-Replica 이중화 노드들
db01        ansible_host={{ db01_host }}        swarm_ip=192.168.101.31
db02        ansible_host={{ db02_host }}        swarm_ip=192.168.101.32

[db_proxy]
# MaxScale / HAProxy 이중화 구성을 위한 프록시 노드 그룹
db_proxy01  ansible_host={{ db_proxy01_host }}  swarm_ip=192.168.101.40
db_proxy02  ansible_host={{ db_proxy02_host }}  swarm_ip=192.168.101.41

[all:vars]
ansible_user=user
ansible_ssh_private_key_file=~/.ssh/id_rsa
