[swarm_managers]
swarm-mg  ansible_host=192.168.1.20 swarm_node_name=web1
swarm-mg2 ansible_host=192.168.1.21 swarm_node_name=web2
swarm-mg3 ansible_host=192.168.1.22 swarm_node_name=web3

[database_nodes]
db01 ansible_host=192.168.101.31
db02 ansible_host=192.168.101.32

[database_proxies]
db_proxy-01 ansible_host=192.168.101.40
db_proxy-02 ansible_host=192.168.101.41

[swarm:children]
swarm_managers

[database:children]
database_nodes
database_proxies

[all:vars]
ansible_user=ubuntu
# 키 파일 경로를 앞선 실습자가 쓰던 파일로 지정합니다.
ansible_ssh_private_key_file=~/ansible-ansible/openstack2.pem

# 172.16.8.100 오픈스택 호스트를 거쳐 내부 가상 가상 네트워크(qrouter)로 우회 접속하는 옵션입니다.
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyCommand="ssh root@172.16.8.100 ''ip netns exec qrouter-3d41fc31-6dbf-4463-a70b-6f6951e18cab /bin/nc %h %p''"'
