[swarm_managers]
# 오픈스택 환경에서는 팀원의 VM 호스트임이나 IP를 적을 수 있도록 플레이스홀더화 합니다.
swarm-mg     ansible_host={{ manager01_host }} swarm_ip=192.168.100.20
swarm-mg02   ansible_host={{ manager02_host }} swarm_ip=192.168.100.21
swarm-mg03   ansible_host={{ manager03_host }} swarm_ip=192.168.100.22

[swarm_workers]
swarm-wk01   ansible_host={{ worker01_host }}  swarm_ip=192.168.100.23
swarm-wk02   ansible_host={{ worker02_host }}  swarm_ip=192.168.100.24

[db_proxy]
db-proxy     ansible_host={{ db_proxy_host }}

[databases]
db01         ansible_host={{ database_host }}

[all:vars]
ansible_user=user
ansible_ssh_private_key_file=~/.ssh/id_rsa
