---
# ========================================================
# [0단계] Common - 전체 인프라 노드 공통 초기 세팅 (Target: All)
# ========================================================
- name: "[0단계] Common Configuration for All Nodes"
  hosts: all
  gather_facts: yes
  roles:
      # - { role: common/update_cache, tags: common }
      # - { role: common/upgrade_packages, tags: common }
    - { role: common/install_utilities, tags: common }
    - { role: common/setup_timezone, tags: common }
    - { role: common/sync_time, tags: common }
    - { role: common/ufw_settings, tags: common }

# ========================================================
# [1단계] Database - MariaDB 가상 인프라 구축 (Target: DB Nodes & Proxies)
# ========================================================
- name: "[1단계] Database Infrastructure Setup"
  hosts: database_nodes, database_proxies
  gather_facts: yes
  roles:
    - { role: database/mariadb_install, tags: db_infra }
    - { role: database/mariadb_configure, tags: db_infra }

# ========================================================
# [2단계] Monitoring - 통합 관제 메트릭 수집 에이전트 배포 (Target: All)
# ========================================================
- name: "[2단계-A] Infrastructure Metrics Agent (Node Exporter)"
  hosts: all
  gather_facts: yes
  roles:
    - { role: monitoring/node_exporter_install, tags: monitoring }
    - { role: monitoring/node_exporter_service, tags: monitoring }

# cAdvisor 단계가 제외되었습니다.

- name: "[2단계-C] Database Metrics Agent (MySQLd Exporter)"
  hosts: database_nodes
  gather_facts: yes
  roles:
    - { role: monitoring/mysqld_exporter_install, tags: db_monitoring }
    - { role: monitoring/mysqld_exporter_service, tags: db_monitoring }
