# Managers: web1~3 | Workers: .23~.25

- targets:
    - 192.168.1.20:9100
    - 192.168.1.21:9100
    - 192.168.1.22:9100
  labels:
    job: swarm_nodes
    role: swarm-manager
    layer: openstack-instance

- targets:
    - 192.168.1.23:9100
    - 192.168.1.24:9100
    - 192.168.1.25:9100
  labels:
    job: swarm_nodes
    role: swarm-worker
    layer: openstack-instance
